### ISSUE TITLE
Bundle can't be installed -- Please check manually

### ISSUE THREAD

**Issue by jacebrowning** [votestakes/proto-rails#18]
This happens on my machine:

```
$ make run
bundle exec foreman start --procfile Procfile.dev --port 3000
18:08:43 web.1   | started with pid 67249
18:08:43 guard.1 | started with pid 67250
18:08:45 guard.1 | /opt/boxen/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'bundler' (>= 0.a) among 153 total gem(s) (Gem::LoadError)
18:08:45 guard.1 | Checked in 'GEM_PATH=/Users/Browning/Programs/votestakes-app/vendor/ruby/2.3.0', execute `gem env` for more information
18:08:45 guard.1 |  from /opt/boxen/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
18:08:45 guard.1 |  from /opt/boxen/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
18:08:45 guard.1 |  from /opt/boxen/rbenv/versions/2.3.0/bin/bundle:22:in `<main>'
18:08:45 - INFO - Bundling...
18:08:45 guard.1 | /opt/boxen/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'bundler' (>= 0.a) among 153 total gem(s) (Gem::LoadError)
18:08:45 guard.1 | Checked in 'GEM_PATH=/Users/Browning/Programs/votestakes-app/vendor/ruby/2.3.0', execute `gem env` for more information
18:08:45 guard.1 |  from /opt/boxen/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
18:08:45 guard.1 |  from /opt/boxen/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
18:08:45 guard.1 |  from /opt/boxen/rbenv/versions/2.3.0/bin/bundle:22:in `<main>'
18:08:45 - INFO - Bundle can't be installed -- Please check manually
18:08:46 web.1   | => Booting Thin
18:08:46 web.1   | => Rails 4.2.5 application starting in development on http://localhost:3000
18:08:46 web.1   | => Run `rails server -h` for more startup options
18:08:46 web.1   | => Ctrl-C to shutdown server
18:08:46 web.1   | Thin web server (v1.6.4 codename Gob Bluth)
18:08:46 web.1   | Maximum connections set to 1024
18:08:46 web.1   | Listening on localhost:3000, CTRL+C to stop
18:08:46 guard.1 | 18:08:46 - INFO - LiveReload is waiting for a browser to connect.
18:08:46 guard.1 | 18:08:46 - INFO - Guard::RSpec is running
18:08:46 guard.1 | 18:08:46 - INFO - Guard is now watching at '/Users/Browning/Programs/votestakes-app'
```

**Comment by jacebrowning** [comment]
I'm just going to remove guard.
